package modelTerminal;
public enum Navigation {
    MAIN,
    TIMER,
    STOPWATCH,
    TIME_CALCULATOR,
    CALENDAR,
    ACTIVE_TASKS,
    RECURRING_TASKS,
    COMPLETED_TASKS,
    ADD_ACTIVE_TASK,
    ADD_RECURRING_TASK,
    DELETE_ACTIVE_TASK,
    DELETE_RECURRING_TASK,
    MARK_TASK_COMPLETED,
    EXIT;
}
